---

- hosts: all
  become: true
  pre_tasks:

  - name: Update packages (ubuntu)
    tags: always
    apt:
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

- hosts: docker
  become: true
  roles:
    - role: docker
  tags: docker

- hosts: postgres
  become: true
  roles:
    - role: postgres
  tags: postgres

- hosts: nginx
  become: true
  roles:
    - role: nginx
  tags: nginx