name: Monitoring service

on:
  workflow_run:
    workflows: ["Build, test and push api gateway image to dockerhub"]
    types:
      - completed

env:
  IMAGE: microservices-monitoring-service
  CONTAINER: ps-monitoring-svc

jobs:

  build-and-publish:
    name: build and publish
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: install dependencies
        working-directory: monitoring-svc
        run: |
          npm install
      - name: build
        working-directory: monitoring-svc
        run: |
          npm run build
          npm run test
  
  push-to-docker-hub:
    name: build and push docker images to dockerhub
    runs-on: ubuntu-latest
    needs: [build-and-publish]
    
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      
      - name: set up QEMU
        uses: docker/setup-qemu-action@v1
    
      - name: set up docker build
        uses: docker/setup-buildx-action@v1
      
      - name: login to dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: build and push
        uses: docker/build-push-action@v2
        with:
          context: ./monitoring-svc
          file: ./monitoring-svc/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE }}:latest