name: Build, test and push store service image to dockerhub

on:
  workflow_run:
    workflows: ["Build, test and push user service image to dockerhub"]
    types:
      - completed

env:
  IMAGE: microservices-store-service
  CONTAINER: ps-store-svc

jobs:

  build-and-publish:
    name: build and publish
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: install dependencies
        working-directory: store-svc
        run: |
          npm install
      - name: build
        working-directory: store-svc
        run: |
          npm run build
          npm run test
  
  push-to-docker-hub:
    name: build and push docker images to dockerhub
    runs-on: ubuntu-latest
    needs: [build-and-publish]
    
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      
      - name: set up QEMU
        uses: docker/setup-qemu-action@v1
    
      - name: set up docker build
        uses: docker/setup-buildx-action@v1

      - name: Cache docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-store-svc-cache
          key: ${{ runner.os }}-store-svc-buildx
      
      - name: login to dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: build and push
        uses: docker/build-push-action@v2
        with:
          context: ./store-svc
          file: ./store-svc/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE }}:latest
          cache-from: type=local,src=/tmp/.buildx-store-svc-cache
          cache-to: type=local,dest=/.buildx-store-svc-cache-new
      
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-store-svc-cache
          mv /tmp/.buildx-store-svc-cache-new /tmp/.buildx-store-svc-cache
